###
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": {
    "value": "testemail@gmail.com"
  },
  "name": "username",
  "role": "ADMIN",
  "address": {
    "street": "Spengergasse",
    "city": "Wien",
    "zipCode": "1050"
  }
}

###

### get all users
GET http://localhost:8080/api/user


###

### get one user
GET http://localhost:8080/api/user/1

###


